upstream tei_backends {
    least_conn;
    server embeddings-1:80;
    server embeddings-2:80;
    server embeddings-3:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://tei_backends;
        proxy_read_timeout 120s;
        proxy_next_upstream error timeout http_502 http_503;
        proxy_next_upstream_tries 3;
    }
}
