apiVersion: v1
kind: Namespace
metadata:
  name: unichat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-minilm
  namespace: unichat
spec:
  replicas: 5
  selector:
    matchLabels:
      app: embedding-minilm
  template:
    metadata:
      labels:
        app: embedding-minilm
    spec:
      containers:
        - name: tei
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
          args:
            - --model-id
            - sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
            - --max-concurrent-requests
            - "2"
            - --max-batch-tokens
            - "1024"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "1500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-lb
  namespace: unichat
spec:
  selector:
    app: embedding-minilm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: embedding-minilm-hpa
  namespace: unichat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: embedding-minilm
  minReplicas: 5
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
